# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Rubocop

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    container: ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: bundle install

    - name: Run Rubocop
      run: bundle exec rake rubocop
